### BASE URL
@baseUrl = http://localhost:3000/api/members

### 1. Criar Membro Completo (Sucesso)
POST {{baseUrl}}/
Content-Type: application/json
Authorization: Bearer seu_token_aqui

{
  "name": "João Silva",
  "birthdate": "1990-05-15",
  "gender": "male",
  "role_id": 1,
  "phone": "11999998888",
  "email": "joao@exemplo.com",
  "image_url": "https://exemplo.com/fotos/joao.jpg",
  "family_id": 1,
  "ministries": []
}

### 2. Criar Membro Mínimo (Sucesso)
POST {{baseUrl}}/
Content-Type: application/json

{
  "name": "Maria Silva",
  "gender": "female",
  "role": "leader",
  "phone": "11988887777",
  "family_id": 1
}

### 3. Tentativa com Dados Inválidos (Erro)
POST {{baseUrl}}/
Content-Type: application/json

{
  "name": "",
  "gender": "",
  "role": "INVALIDROLE",
  "phone": 123, 
  "family_id": "abc" 
}

### 4. Listar Membros (Todos)
GET {{baseUrl}}/
Accept: application/json

### 5. Listar Membros com Filtro
GET {{baseUrl}}/?search=João
Accept: application/json

### 6. Buscar Membro por ID
GET {{baseUrl}}/1
Accept: application/json

### 7. Tentativa Buscar Membro Inexistente
GET {{baseUrl}}/9999
Accept: application/json

### 8. Pegar as minhas informações
GET {{baseUrl}}/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsInJvbGUiOiJwYXN0b3IiLCJpYXQiOjE3NTIxNjgyMDV9.IkuvxXFiTqCTii5xKV4uQU8N-7YY-HUtHlN2Bj0IT-w

{}